<?php
/*
 *  TRINITY FRAMEWORK <http://www.invenzzia.org>
 *
 * This file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE. It is also available through
 * WWW at this URL: <http://www.invenzzia.org/license/new-bsd>
 *
 * Copyright (c) Invenzzia Group <http://www.invenzzia.org>
 * and other contributors. See website for details.
 *
 * $Id$
 */

namespace Trinity\Garage\Config;
use Trinity\Garage\Config\Loader as Loader;

/**
 * The configuration loader which loads the configuration from INI
 * files.
 */
class Loader_Ini implements Loader
{
	/**
	 * The configuration file name.
	 * @var string
	 */
	private $_filename;

	/**
	 * The class constructor initializes the loader by providing the filename
	 * which the configuration should be loaded from.
	 *
	 * @param string $filename The path to the configuration file.
	 */
	public function __construct($filename)
	{
		$this->_filename = (string)$filename;
	} // end __construct();

	/**
	 * Returns the type of the output generated by this loader.
	 */
	public function getOutputType()
	{
		return Loader::PLAIN_LIST;
	} // end getOutputType();

	/**
	 * Loads the configuration for the specified environment.
	 *
	 * @param string $environment The environment name.
	 * @return array
	 */
	public function loadConfig($environment)
	{
		if(!\is_readable($this->_filename))
		{
			// TODO: EXCEPTION!
			throw new \Exception('Cannot open the configuration file '.$this->_filename.' for reading.');
		}
		$file = \parse_ini_file($this->_filename, true);

		if(!\is_array($file) || !isset($file[$environment]))
		{
			// TODO: EXCEPTION!
			throw new \Exception('The configuration environment '.$environment.' is missing.');
		}

		return $file[$environment];
	} // end loadConfig();
} // end Loader_Ini;