<?php
/*
 *  TRINITY FRAMEWORK <http://www.invenzzia.org>
 *
 * This file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE. It is also available through
 * WWW at this URL: <http://www.invenzzia.org/license/new-bsd>
 *
 * Copyright (c) Invenzzia Group <http://www.invenzzia.org>
 * and other contributors. See website for details.
 */
namespace Trinity\WebUtils\Model\Interfaces;
use \Countable;

/**
 * Allows the model to introduce itself.
 *
 * @author Tomasz Jędrzejewski
 */
interface Identification
{
	/**
	 * Should return the unique model name that could be used for various
	 * purposes (i.e. selecting the translation group).
	 *
	 * @return string
	 */
	public function myName();
} // end Identification;

/**
 * The interface for displaying a grid of rows.
 *
 * @author Tomasz Jędrzejewski
 */
interface Grid
{
	/**
	 * Returns the column headers.
	 */
	public function getColumnHeaders();

	/**
	 * Returns the items.
	 */
	public function getItems();
} // end Grid;

/**
 * Models implementing this interface can return simplified information
 * about a particular row. The simplified information should include:
 *  - id
 *  - title
 *  - entityName (i.e. if the model returns users, it should return "user")
 *
 * @author Tomasz Jędrzejewski
 */
interface Brief
{
	/**
	 * Returns brief information about a particular row.
	 * @return array
	 */
	public function getBriefInformation();
} // end Brief;

/**
 * Persistent identity allows to communicate with the session storage.
 *
 * @author Tomasz Jędrzejewski
 */
interface PersistentIdentity
{
	public function getPersistentIdentity($id, $accountType);
} // end PersistentIdentity;

/**
 * Interface for interaction with forms and various select boxes.
 *
 * @author Tomasz Jędrzejewski
 */
interface Selectable
{
	/**
	 * Returns the array of available choices.
	 *
	 * @return array
	 */
	public function getSelectOptions();

	/**
	 * Verifies if the selected choice exists.
	 *
	 * @param int $id The identifier to check.
	 * @return boolean
	 */
	public function selectionExists($id);
} // end Previewable;

/**
 * Interface for communicating with CRUD controllers. It represents entities
 * that allow to add new rows.
 *
 * @author Tomasz Jędrzejewski
 */
interface Addable
{
	public function addItem($data);
} // end Addable;

/**
 * Interface for communicating with CRUD controllers. It represents entities
 * that allow to edit existing rows.
 *
 * @author Tomasz Jędrzejewski
 */
interface Editable
{
	public function getItemForEdit();
	public function editItem($data);
} // end Editable;

/**
 * Interface for communicating with CRUD controllers. It represents entities
 * that allow to remove rows.
 *
 * @author Tomasz Jędrzejewski
 */
interface Removable
{
	public function removeItem();
} // end Removable;

/**
 * The rows from this model can be moved up and down.
 *
 * @author Tomasz Jędrzejewski
 * @copyright Invenzzia Group <http://www.invenzzia.org/> and contributors.
 * @license http://www.invenzzia.org/license/new-bsd New BSD License
 */
interface Movable
{
	/**
	 * Move the row up, if possible.
	 */
	public function moveUp();

	/**
	 * Move the row down, if possible.
	 */
	public function moveDown();
} // end Movable;

/**
 * Interface for models, where entities can be paginated.
 *
 * @author Tomasz Jędrzejewski
 */
interface Paginable extends Countable
{
	public function setLimit($limit, $offset);
} // end Paginable;

/**
 * Interface for models which want to display some details about
 * a row.
 *
 * @author Tomasz Jędrzejewski
 */
interface Details
{
	/**
	 * Returns the list of detail categories generated by this model.
	 * The list should be an array of category keys accepted by
	 * <tt>getDetailCategory()</tt> and their titles.
	 *
	 * @return array
	 */
	public function getAvailableDetailCategories();

	/**
	 * Returns a list of row details in a given category. The list should
	 * be an associative array of pairs <tt>title</tt> => <tt>value</tt>.
	 *
	 * @return array
	 */
	public function getDetailCategory($categoryKey);
} // end Details;

/**
 * Interface for models, where entities can be paginated.
 *
 * @author Tomasz Jędrzejewski
 */
interface ManyToMany extends Paginable, Identification, Brief
{
	/**
	 * Lists the subitems for the given item in many-to-many relationship.
	 *
	 * @return array
	 */
	public function listSubitems();

	/**
	 * Lists the unselected items.
	 *
	 * @return array
	 */
	public function listUnselected();

	/**
	 * Adds a new subitem with the given ID to the relationship.
	 */
	public function add($id);

	/**
	 * Removes the subitem with the
	 */
	public function remove($id);
} // end ManyToMany;

/**
 * Indicates that the modelled entity is connected with a one-to-many
 * relationship. This interface allows to check if the parent object
 * actually exists and load it.
 *
 * @author Tomasz Jędrzejewski
 */
interface HasParent
{
	/**
	 * Returns brief information about the parent.
	 * @return array
	 */
	public function getParentInformation();
} // end HasParent;

/**
 * Indicates that this model needs the logged user identity in order
 * to work correctly. The identity should be injected to it.
 *
 * @author Tomasz Jędrzejewski
 */
interface UsesIdentity
{
	/**
	 * Sets the user identity.
	 *
	 * @param array|object $identity The user identity.
	 */
	public function setIdentity($identity);
	/**
	 * Returns the model identity.
	 *
	 * @return array|object
	 */
	public function getIdentity();
} // end UsesIdentity;